package dtos;

public enum InformationClassDto {
    PERSONAL_INFORMATION,
    RELATIONSHIPS_INFORMATION,
    SCHOOL_INFORMATION,
    FACULTY_INFORMATION,
    FREE_TIME_INFORMATION,
    GASTRONOMY_INFORMATION
}
